"""initial database

Revision ID: 06a92f0c1b88
Revises: 
Create Date: 2026-08-07 09:59:18.472400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '06a92f0c1b88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint(
        'uq_settings_configs_user_id',
        ['user_id']
    )

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('importance', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('widgets')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widgets', sqlite.JSON(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('importance')
        batch_op.drop_column('done')
        batch_op.drop_column('private')
        batch_op.drop_column('urgency')
        batch_op.drop_column('deadline')
        batch_op.drop_column('tags')
        batch_op.drop_column('text')

    with op.batch_alter_table('settings_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
