"""drop orphaned play2gether tables

Revision ID: da526f22858a
Revises: 06a92f0c1b88
Create Date: 2026-08-25 18:32:03.246670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'da526f22858a'
down_revision = '06a92f0c1b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play2gether_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play2gether_events_code'))

    op.drop_table('play2gether_events')
    op.drop_table('play2gether_rooms')
    op.drop_table('play2gether_configs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play2gether_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('apps_config_id', sa.INTEGER(), nullable=False),
    sa.Column('queue', sqlite.JSON(), nullable=True),
    sa.Column('current_index', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.FLOAT(), nullable=True),
    sa.Column('playing', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['apps_config_id'], ['apps_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play2gether_rooms',
    sa.Column('code', sa.VARCHAR(length=8), nullable=False),
    sa.Column('state', sqlite.JSON(), nullable=False),
    sa.Column('version_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('play2gether_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=8), nullable=False),
    sa.Column('event', sa.VARCHAR(length=40), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['play2gether_rooms.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play2gether_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play2gether_events_code'), ['code'], unique=False)

    # ### end Alembic commands ###
